import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "The Sourob",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased  bg-cover bg-no-repeat bg-center min-h-screen bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
